version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: boela_user
      POSTGRES_PASSWORD: boela_password
      POSTGRES_DB: boela_db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
